apiVersion: batch/v1
kind: Job
metadata:
  name: sync-fail-hook-flock
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: flock-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Content-Type: application/json"
          - "-d"
          - "{\"text\": \"Sync failed.\"}"
          - "https://api.flock.com/hooks/sendMessage/8dbfc174-b231-4817-b3fa-861b4489f719"
      restartPolicy: Never
  backoffLimit: 2