apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustom-nginx-prod
  namespace: default
spec:
  destination:
    name: 'gke_gke-test-395604_us-central1-c_cluster-1'
    namespace: "kustomize-nginx-prod"
  source:
    path: kustomize/kustomize-nginx-app/overlays/prod
    repoURL: 'git@github.com:desert3agle/argo-assgn.git'
    targetRevision: HEAD
    kustomize:
      namespace: kustomized-nginx-prod
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true